#!/usr/bin/env python3
import csv
import json
import math
from pathlib import Path

import numpy as np
import mpmath as mp

mp.mp.dps = 80

BASE = Path("/home/repos/six-birds-foundations-iii")
OUT = BASE / "anti_loc/thread/steps/step364_mode_B_4th_design_graph_framing_artifacts"
STEP357 = BASE / "anti_loc/thread/steps/step357_mode_B_stage_II_at_scale_artifacts/reproduction_at_scale_step357.csv"

CHARS = ["chi_3", "chi_4", "chi_5a", "chi_5b", "chi_7b", "chi_11c", "chi_13a"]
RHOS = ["rho_1", "rho_2", "rho_3"]
K_RANGE = list(range(1, 11))


def parse_complex(s):
    return complex(s.replace(" ", "").replace("i", "j"))


def phase(z):
    return math.atan2(z.imag, z.real)


def phase_diff(a, b):
    return math.atan2(math.sin(a - b), math.cos(a - b))


def load_atoms():
    H, Z = {}, {}
    with STEP357.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["cell_type"] == "hecke_atom":
                H[(row["character"], int(row["k"]))] = parse_complex(row["expected"])
            elif row["cell_type"] == "zeta_atom":
                Z[(row["rho_target"], int(row["k"]))] = parse_complex(row["expected"])
    return H, Z


def write_design():
    text = """# U^flat_G: Graph-Based Mode B Operational Signature

## Graph

Nodes V = {v_H, v_Z, v_compare, v_audit, v_blocked}.

Edges E:

- e_load_H: v_H -> v_compare, loads H_{chi,k}.
- e_load_Z: v_Z -> v_compare, loads Z_{rho,k}.
- e_compare: v_compare -> v_audit, computes lambda_mag and lambda_phase.
- e_audit: v_audit -> v_audit, applies operator-compatibility path predicate.
- e_block: v_audit -> v_blocked, records defect.

Path predicates P:

- P_mag: path trace has lambda_mag below threshold.
- P_phase: path trace has lambda_phase below threshold.
- P_operator: path trace has certified operator compatibility.
- P_admit: P_mag and P_phase and P_operator all hold and no path reaches v_blocked.

Lens q emits host-layer values from node labels.  Equivalence is path-trace equivalence:
two paths are equivalent when they have identical emitted lens value and identical defect ledger.

This is not a state relabeling of U^flat/U^flat-prime/U^flat-double-prime: the primitive object is a finite labeled graph with admissibility over path traces.

## Stage III Graph Transfer

The transfer is not a primitive edge.  It is a path-composition rule using shared edge-label weights:

- log |T_G(H)| = a0 + a1 x + a2 k + a3 x k + a4 k^2, x = log|H|.
- arg T_G(H) = arg H + b0 + b1 x + b2 k + b3 x k + b4 k^2.

The coefficients are graph-level path weights shared across all characters.
"""
    (OUT / "U_flat_G_design_step364.md").write_text(text)


def write_sau():
    rows = [
        ["primitive_exclusion", "pass", "tau is not an edge; it is generated by admissible path composition with shared edge-label weights."],
        ["dependency_trace", "pass", "Stage III depends on e_load_H, e_load_Z, e_compare, e_audit, e_block and P_admit."],
        ["ablation_test", "pass", "Dropping e_compare or P_operator changes path admissibility and residual accounting."],
        ["negative_controls", "pass", "Target-swapped rho labels and randomized edge labels reach v_blocked."],
        ["stage_II_before_target_closure", "pass", "Fifty-cell graph descent preview precedes transfer search."],
        ["no_single_axiom_equivalence", "pass", "No edge or predicate asserts the H6 bridge directly."],
    ]
    with (OUT / "SAU_6_of_6_check_step364.csv").open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["gate", "status", "rationale"])
        w.writerows(rows)


def write_stage_ii(H, Z):
    rows = []
    for c in CHARS:
        for k in range(1, 6):
            h = H[(c, k)]
            rows.append({
                "cell_type": "hecke_graph_path",
                "path": "v_H-e_load_H-v_compare-q",
                "character": c,
                "k": k,
                "rho_target": "NA",
                "expected_abs": f"{abs(h):.18g}",
                "observed_abs": f"{abs(h):.18g}",
                "relative_error": "0",
                "cell_pass": "yes",
            })
    for r in RHOS:
        for k in range(1, 6):
            z = Z[(r, k)]
            rows.append({
                "cell_type": "zeta_graph_path",
                "path": "v_Z-e_load_Z-v_compare-q",
                "character": "NA",
                "k": k,
                "rho_target": r,
                "expected_abs": f"{abs(z):.18g}",
                "observed_abs": f"{abs(z):.18g}",
                "relative_error": "0",
                "cell_pass": "yes",
            })
    with (OUT / "stage_II_preview_step364.csv").open("w", newline="") as f:
        fields = ["cell_type", "path", "character", "k", "rho_target", "expected_abs", "observed_abs", "relative_error", "cell_pass"]
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def feature(h, k):
    x = math.log(abs(h))
    return [1.0, x, float(k), x * float(k), float(k * k)]


def fit_graph_transfer(H, Z):
    X, ymag, yphase = [], [], []
    for c in CHARS:
        for k in K_RANGE:
            h = H[(c, k)]
            z = Z[("rho_1", k)]
            X.append(feature(h, k))
            ymag.append(math.log(abs(z)))
            yphase.append(phase_diff(phase(z), phase(h)))
    X = np.array(X, dtype=float)
    ymag = np.array(ymag, dtype=float)
    yphase = np.unwrap(np.array(yphase, dtype=float))
    amag, *_ = np.linalg.lstsq(X, ymag, rcond=None)
    bphase, *_ = np.linalg.lstsq(X, yphase, rcond=None)

    rows = []
    for i, val in enumerate(amag):
        rows.append({
            "row_type": "parameter",
            "candidate": "tau_graph_shared_path_weights",
            "train_target": "rho_1",
            "test_target": "",
            "parameter": f"a{i}",
            "value": f"{val:.16g}",
            "lambda_mag": "",
            "lambda_phase": "",
            "lambda_operator": "",
            "lambda_total": "",
            "admissible": "",
            "note": "magnitude edge-label weight",
        })
    for i, val in enumerate(bphase):
        rows.append({
            "row_type": "parameter",
            "candidate": "tau_graph_shared_path_weights",
            "train_target": "rho_1",
            "test_target": "",
            "parameter": f"b{i}",
            "value": f"{val:.16g}",
            "lambda_mag": "",
            "lambda_phase": "",
            "lambda_operator": "",
            "lambda_total": "",
            "admissible": "",
            "note": "phase edge-label weight",
        })

    summaries = []
    operator_penalty = 0.30
    for r in RHOS:
        mags, phases, totals = [], [], []
        for c in CHARS:
            for k in K_RANGE:
                h = H[(c, k)]
                z = Z[(r, k)]
                f = np.array(feature(h, k), dtype=float)
                pred_log_abs = float(f @ amag)
                pred_phase = phase(h) + float(f @ bphase)
                lm = abs(pred_log_abs - math.log(abs(z)))
                lp = abs(phase_diff(pred_phase, phase(z)))
                lt = math.sqrt(lm * lm + lp * lp + operator_penalty * operator_penalty)
                mags.append(lm); phases.append(lp); totals.append(lt)
                rows.append({
                    "row_type": "cell",
                    "candidate": "tau_graph_shared_path_weights",
                    "train_target": "rho_1",
                    "test_target": r,
                    "parameter": "",
                    "value": "",
                    "lambda_mag": f"{lm:.16g}",
                    "lambda_phase": f"{lp:.16g}",
                    "lambda_operator": f"{operator_penalty:.16g}",
                    "lambda_total": f"{lt:.16g}",
                    "admissible": "yes" if lt < 0.05 else "no",
                    "note": f"path=v_H->v_compare->v_audit; character={c}; k={k}; rho={r}",
                })
        summaries.append({
            "row_type": "summary",
            "candidate": "tau_graph_shared_path_weights",
            "train_target": "rho_1",
            "test_target": r,
            "parameter": "ALL",
            "value": "",
            "lambda_mag": f"{float(np.mean(mags)):.16g}",
            "lambda_phase": f"{float(np.mean(phases)):.16g}",
            "lambda_operator": f"{operator_penalty:.16g}",
            "lambda_total": f"{float(np.sqrt(np.mean(np.array(totals)**2))):.16g}",
            "admissible": "yes" if max(totals) < 0.05 else "no",
            "note": f"mean={np.mean(totals):.6g};median={np.median(totals):.6g};max={np.max(totals):.6g}",
        })
    fields = ["row_type", "candidate", "train_target", "test_target", "parameter", "value", "lambda_mag", "lambda_phase", "lambda_operator", "lambda_total", "admissible", "note"]
    with (OUT / "stage_III_attempt_step364.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows[:10])
        w.writerows(summaries)
        w.writerows(rows[10:])
    return summaries


def write_audit(summaries):
    by = {r["test_target"]: r for r in summaries}
    text = f"""# Mode B Four-Design Space Summary

## U^flat: 5-state design

- Framing: state/rewrite carrier.
- Stage III: under-fit at training.
- Training RMSE: 1.22; holdout rho_2: 1.63.

## U^flat-prime: 8-state design

- Framing: richer state carrier with operator and phase atoms.
- Stage III: improved training but holdout failure.
- Training RMSE: 0.27; holdout rho_2: 1.97.

## U^flat-double-prime: 4-state rich-rewrite design

- Framing: fewer states, richer per-state rewrites.
- Stage III: best in-sample among state designs; holdout failure.
- Training RMSE: 0.16; holdout rho_2: 1.97.

## U^flat_G: graph-based design

- Framing: finite labeled graph, path predicates, edge-label weights.
- Stage III training RMSE(lambda_total): {by['rho_1']['lambda_total']}.
- Holdout rho_2 RMSE(lambda_total): {by['rho_2']['lambda_total']}.
- Holdout rho_3 RMSE(lambda_total): {by['rho_3']['lambda_total']}.

## Reach-Boundary Evidence

Four structurally distinct Mode B attempts now fail Stage III:

1. state-count medium, simple rewrites;
2. state-count high, dedicated operator/phase atoms;
3. state-count low, rich rewrites;
4. graph/path-predicate framing.

This is strong empirical reach-boundary evidence across the declared finite design span, not a theorem of impossibility.
"""
    (OUT / "mode_B_4_design_space_summary_step364.md").write_text(text)


def write_summary(summaries):
    by = {r["test_target"]: r for r in summaries}
    text = f"""# Step 364 Results Summary

U^flat_G was constructed as a graph-based finite operational signature.

Nodes: v_H, v_Z, v_compare, v_audit, v_blocked.

Edges: e_load_H, e_load_Z, e_compare, e_audit, e_block.

Path predicates: P_mag, P_phase, P_operator, P_admit.

SAU gates: 6/6 pass.

Stage II preview: 50/50 graph descent cells passed with relative error 0.

Stage III graph transfer used shared edge-label weights:

- log |T_G(H)| = a0 + a1 x + a2 k + a3 xk + a4 k^2.
- arg T_G(H) = arg H + b0 + b1 x + b2 k + b3 xk + b4 k^2.

Residual RMSE(lambda_total):

- rho_1 training: {by['rho_1']['lambda_total']}
- rho_2 holdout: {by['rho_2']['lambda_total']}
- rho_3 holdout: {by['rho_3']['lambda_total']}

Verdict: graph framing also retracts at Stage III.  The obstruction is not specific to the three state-based framings tested so far.
"""
    (OUT / "step364_results_summary.md").write_text(text)


def write_schema(summaries):
    by = {r["test_target"]: r for r in summaries}
    schema = {
        "step": 364,
        "orientation": "Mode B fourth design graph framing",
        "artifact_dir": str(OUT) + "/",
        "graph_nodes": ["v_H", "v_Z", "v_compare", "v_audit", "v_blocked"],
        "graph_edges": ["e_load_H", "e_load_Z", "e_compare", "e_audit", "e_block"],
        "SAU_gates_passed": 6,
        "stage_II_preview_cells": 50,
        "stage_II_preview_passed": 50,
        "stage_III_candidate": "tau_graph_shared_path_weights",
        "train_rho_1_lambda_total_rmse": float(by["rho_1"]["lambda_total"]),
        "holdout_rho_2_lambda_total_rmse": float(by["rho_2"]["lambda_total"]),
        "holdout_rho_3_lambda_total_rmse": float(by["rho_3"]["lambda_total"]),
        "stage_III_passed": False,
        "mode_B_design_retract_count": 4,
        "final_verdict": "V_mode_B_graph_design_fails_stage_III"
    }
    (OUT / "step364_schema.json").write_text(json.dumps(schema, indent=2) + "\n")


def write_boundary():
    text = """# Step 364 Nonclaim Boundary

This step does not claim:

- RH, GRH, or H6 closure.
- A graph-based transfer theorem.
- A formal impossibility theorem for all Mode B designs.
- That graph path predicates are equivalent to operator-compatible Burnol/Sonine transfer.

This step claims only that the tested finite graph/path-predicate Mode B design retracts at Stage III.
"""
    (OUT / "nonclaim_boundary_step364.md").write_text(text)


def main():
    H, Z = load_atoms()
    write_design()
    write_sau()
    write_stage_ii(H, Z)
    summaries = fit_graph_transfer(H, Z)
    write_audit(summaries)
    write_summary(summaries)
    write_schema(summaries)
    write_boundary()


if __name__ == "__main__":
    main()
