#!/usr/bin/env python3
"""Build per-axis paper inventory TOMLs and mechanization queue CSVs.

Reads source_items.jsonl plus an inlined status mapping (curated below)
and emits:
- formalization/inventory/duality_confinement_paper_inventory.toml
- formalization/inventory/rh_paper_inventory.toml
- formalization/traceability/queue_duality_confinement.csv
- formalization/traceability/queue_rh.csv

Run with `--check` to validate that the committed files match what
the script would generate (used by Phase A's seal step and any
downstream CI).

Status field allowlist:
  mechanize_now, obligation, out_of_scope_rh, out_of_scope_ns,
  support_only, nonclaim
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY_DIR = ROOT / "formalization" / "inventory"
TRACEABILITY_DIR = ROOT / "formalization" / "traceability"
SOURCE_ITEMS = INVENTORY_DIR / "source_items.jsonl"

DC_TOML = INVENTORY_DIR / "duality_confinement_paper_inventory.toml"
RH_TOML = INVENTORY_DIR / "rh_paper_inventory.toml"
QUEUE_DC = TRACEABILITY_DIR / "queue_duality_confinement.csv"
QUEUE_RH = TRACEABILITY_DIR / "queue_rh.csv"


# Per-axis (line_start, line_end, "Section title") tuples. Populate as
# the duality_confinement and RH paper LaTeX sources reach label-stable form;
# leave empty until then so the build is gated on real content.
DC_SECTIONS: list[tuple[int, int, str]] = []
RH_SECTIONS: list[tuple[int, int, str]] = []


# Curated intended_status per paper_label. Defaults applied by kind below for any
# label not listed here. Populate as labels emerge in the paper drafts.
STATUS_OVERRIDES: dict[str, str] = {}


def find_section(axis: str, line: int) -> str:
    sections = DC_SECTIONS if axis == "duality_confinement" else RH_SECTIONS
    for start, end, name in sections:
        if start <= line <= end:
            return name
    return "<unknown>"


def default_status(env_kind: str) -> str:
    if env_kind == "nonclaim":
        return "nonclaim"
    if env_kind == "remark":
        return "nonclaim"
    if env_kind == "warning":
        return "nonclaim"
    if env_kind == "obligation":
        return "obligation"
    return "mechanize_now"


def intended_status(label: str, env_kind: str) -> str:
    if label in STATUS_OVERRIDES:
        return STATUS_OVERRIDES[label]
    return default_status(env_kind)


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


AXIS_PRETTY_NAMES = {
    "duality_confinement": "Duality Confinement",
    "rh": "RH",
}


def render_toml(axis: str, entries: list[dict]) -> str:
    pretty = AXIS_PRETTY_NAMES.get(axis, axis)
    lines = [
        f"# Per-axis paper inventory for the {pretty} paper.",
        "# Generated by scripts/build_paper_inventories.py from source_items.jsonl.",
        "#",
        "# Schema (per entry):",
        f"#   paper_label    = \"<kind>:{axis}:<short-name>\"",
        "#   kind           = definition | theorem | lemma | proposition | corollary",
        "#                  | nonclaim | obligation | remark | warning",
        "#   section        = \"<section title verbatim>\"",
        "#   intended_status = mechanize_now | obligation | out_of_scope_recognition_source",
        "#                   | out_of_scope_meta | support_only | nonclaim",
        "#   required       = true | false",
        "#   line_start     = <int>",
        "#   line_end       = <int>",
        f"#   source_file    = \"anti_loc/extracted_math/{axis}_<name>.md\"",
        "#   statement_hash = \"<short hash>\"",
        "#   duplicate_of   = \"\"              # empty unless this row dedupes another",
        "",
    ]
    for entry in entries:
        lines.append("[[entry]]")
        lines.append(f"paper_label = {toml_string(entry['paper_label'])}")
        lines.append(f"kind = {toml_string(entry['kind'])}")
        lines.append(f"section = {toml_string(entry['section'])}")
        lines.append(f"intended_status = {toml_string(entry['intended_status'])}")
        lines.append(f"required = {'true' if entry['required'] else 'false'}")
        lines.append(f"line_start = {entry['line_start']}")
        lines.append(f"line_end = {entry['line_end']}")
        lines.append(f"source_file = {toml_string(entry['source_file'])}")
        lines.append(f"statement_hash = {toml_string(entry['statement_hash'])}")
        lines.append(f"duplicate_of = {toml_string('')}")
        lines.append("")
    return "\n".join(lines)


def write_toml(path: Path, axis: str, entries: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_toml(axis, entries), encoding="utf-8")


def render_queue(entries: list[dict]) -> str:
    queue_entries = [e for e in entries if e["intended_status"] == "mechanize_now"]
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(["order", "paper_label", "kind", "section", "line_start", "source_file"])
    for order, entry in enumerate(queue_entries, start=1):
        writer.writerow(
            [
                order,
                entry["paper_label"],
                entry["kind"],
                entry["section"],
                entry["line_start"],
                entry["source_file"],
            ]
        )
    return buffer.getvalue()


def write_queue(path: Path, entries: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_queue(entries), encoding="utf-8")


def collect_entries() -> tuple[list[dict], list[dict]]:
    records = [
        json.loads(line)
        for line in SOURCE_ITEMS.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    duality_confinement_entries: list[dict] = []
    rh_entries: list[dict] = []
    for record in sorted(records, key=lambda r: (r["paper_axis"], r["line_start"])):
        label = str(record["latex_label"])
        kind = str(record["env_kind"])
        axis = str(record["paper_axis"])
        line = int(record["line_start"])
        entry = {
            "paper_label": label,
            "kind": kind,
            "section": find_section(axis, line),
            "intended_status": intended_status(label, kind),
            "required": True,
            "line_start": line,
            "line_end": int(record["line_end"]),
            "source_file": str(record["source_file"]),
            "statement_hash": str(record["statement_hash"]),
        }
        if axis == "duality_confinement":
            duality_confinement_entries.append(entry)
        else:
            rh_entries.append(entry)
    return duality_confinement_entries, rh_entries


def check() -> int:
    """Validate the committed inventory TOMLs and queue CSVs match what we
    would generate from the current source_items.jsonl."""
    errors: list[str] = []
    duality_confinement_entries, rh_entries = collect_entries()
    for path, axis, entries in [
        (DC_TOML, "duality_confinement", duality_confinement_entries),
        (RH_TOML, "rh", rh_entries),
    ]:
        if not path.exists():
            errors.append(f"missing {path.relative_to(ROOT)}; rerun build_paper_inventories")
            continue
        expected = render_toml(axis, entries)
        if path.read_text(encoding="utf-8") != expected:
            errors.append(f"{path.relative_to(ROOT)} is stale; rerun build_paper_inventories")
    for path, entries in [(QUEUE_DC, duality_confinement_entries), (QUEUE_RH, rh_entries)]:
        if not path.exists():
            errors.append(f"missing {path.relative_to(ROOT)}; rerun build_paper_inventories")
            continue
        expected = render_queue(entries)
        if path.read_text(encoding="utf-8") != expected:
            errors.append(f"{path.relative_to(ROOT)} is stale; rerun build_paper_inventories")
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("paper inventories and queues are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate committed inventory TOMLs and queue CSVs against current source_items.jsonl",
    )
    args = parser.parse_args()
    if args.check:
        return check()

    duality_confinement_entries, rh_entries = collect_entries()
    write_toml(DC_TOML, "duality_confinement", duality_confinement_entries)
    write_toml(RH_TOML, "rh", rh_entries)
    write_queue(QUEUE_DC, duality_confinement_entries)
    write_queue(QUEUE_RH, rh_entries)

    print(f"wrote {len(duality_confinement_entries)} duality_confinement entries → {DC_TOML.relative_to(ROOT)}")
    print(f"wrote {len(rh_entries)} rh entries → {RH_TOML.relative_to(ROOT)}")
    print(f"wrote duality_confinement queue ({sum(1 for e in duality_confinement_entries if e['intended_status'] == 'mechanize_now')} items) → {QUEUE_DC.relative_to(ROOT)}")
    print(f"wrote rh queue ({sum(1 for e in rh_entries if e['intended_status'] == 'mechanize_now')} items) → {QUEUE_RH.relative_to(ROOT)}")

    print()
    print("Status breakdown:")
    for axis_name, entries in [("duality_confinement", duality_confinement_entries), ("rh", rh_entries)]:
        counts: dict[str, int] = {}
        for e in entries:
            counts[e["intended_status"]] = counts.get(e["intended_status"], 0) + 1
        print(f"  {axis_name}: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
