#!/usr/bin/env python3
"""Step 276: Branch A Phi(sigma, ell) sweep.

The baseline operator is the inherited steps 217-220/246 local-window
approximation to the Sonine projection:

    P_infty ~= I - sinc_band - PSWF_tail,

where the PSWF basis is generated by the step 215 machinery.  mpmath is kept at
80 dps for constants and reproducibility; the inherited quadrature/operator
matrix implementation is NumPy double precision, as in steps 220 and 246.
"""

from __future__ import annotations

import csv
import importlib.util
import json
import math
import sys
from pathlib import Path

import mpmath as mp
import numpy as np
from numpy.polynomial.legendre import leggauss


mp.mp.dps = 80

ROOT = Path("/home/repos/six-birds-foundations-iii")
ART = ROOT / "anti_loc/thread/steps/step276_branch_A_universality_artifacts"
STEP215_SCRIPT = ROOT / "anti_loc/thread/steps/step215_branch_A_weyl_extended_artifacts/compute_weyl_extended_step215.py"

T_CENTER = 5000.0
N_GRID = 1400
LOCAL_WINDOW = 80.0
N_PSWF_TERMS = 24
LAMBDA = 1.0
STEP220_BASELINE = 0.4904766190


def load_step215_module():
    spec = importlib.util.spec_from_file_location("step215_weyl", STEP215_SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load Step 215 module")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["step215_weyl"] = mod
    spec.loader.exec_module(mod)
    return mod


def sinc_kernel(x: np.ndarray | float) -> np.ndarray | float:
    arr = np.asarray(x, dtype=float)
    out = np.empty_like(arr, dtype=float)
    mask = np.abs(arr) < 1e-12
    out[mask] = LAMBDA / math.pi
    out[~mask] = np.sin(LAMBDA * arr[~mask]) / (math.pi * arr[~mask])
    if np.isscalar(x):
        return float(out)
    return out


def l2_inner(f: np.ndarray, g: np.ndarray, weights: np.ndarray) -> complex:
    return complex(np.sum(weights * np.conjugate(f) * g) / (2.0 * math.pi))


def l2_norm(f: np.ndarray, weights: np.ndarray) -> float:
    return math.sqrt(max(0.0, l2_inner(f, f, weights).real))


def local_grid(center: float = T_CENTER, window: float = LOCAL_WINDOW) -> tuple[np.ndarray, np.ndarray]:
    x, w = leggauss(N_GRID)
    tau = center + window * x
    weights = window * w
    return tau, weights


def packet(tau: np.ndarray, weights: np.ndarray, center: float, sigma: float) -> np.ndarray:
    z = np.exp(-((tau - center) ** 2) / (2.0 * sigma * sigma))
    z[np.abs(tau - center) > 3.0 * sigma] = 0.0
    nrm = l2_norm(z.astype(np.complex128), weights)
    return (z / max(nrm, 1e-300)).astype(np.complex128)


def make_sonine_operator(tau: np.ndarray, weights: np.ndarray, psis: np.ndarray):
    sinc_mat = sinc_kernel(tau[:, None] - tau[None, :])
    psi_conj = np.conjugate(psis)

    def p_operator(f: np.ndarray) -> np.ndarray:
        sinc_part = sinc_mat.dot(weights * f)
        inner = psi_conj.dot(weights * f)
        pswf_part = psis.T.dot(inner)
        return f - sinc_part - pswf_part

    return p_operator


def phi_value(tau: np.ndarray, weights: np.ndarray, p_operator, sigma: float, ell: float) -> tuple[float, float]:
    u = packet(tau, weights, T_CENTER, sigma)
    pu = p_operator(u)
    phase = np.exp(1j * ell * tau)
    h = phase * pu - p_operator(phase * pu)
    return l2_norm(h, weights), l2_norm(pu, weights)


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    if not rows:
        raise ValueError(f"no rows for {path}")
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    ART.mkdir(parents=True, exist_ok=True)
    mod = load_step215_module()
    tau, weights = local_grid()
    psis = mod.build_psi_matrix(tau, n_terms=N_PSWF_TERMS)
    p_operator = make_sonine_operator(tau, weights, psis)

    sigmas = [0.10, 0.20, 0.30, 0.35, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]
    ells = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0]

    rows: list[dict[str, object]] = []
    for sigma in sigmas:
        for ell in ells:
            phi, pu_norm = phi_value(tau, weights, p_operator, sigma, ell)
            rows.append(
                {
                    "sigma": f"{sigma:.8f}",
                    "ell": f"{ell:.8f}",
                    "Phi": f"{phi:.17e}",
                    "P_u_norm": f"{pu_norm:.17e}",
                    "T": f"{T_CENTER:.8f}",
                    "mpmath_dps": "80",
                    "quadrature": f"GL{N_GRID}_double_local_window",
                    "pswf_terms": str(N_PSWF_TERMS),
                    "filter_family": "burnol_sonine_pswf24_baseline",
                }
            )
        print(f"sigma={sigma:.2f} complete")

    write_csv(ART / "phi_max_sweep_step276.csv", rows)
    best = max(rows, key=lambda r: float(r["Phi"]))

    # Local finite-difference gradient around the inherited maximizer.
    local_points = {
        "center": (0.35, 2.0),
        "sigma_minus": (0.30, 2.0),
        "sigma_plus": (0.40, 2.0),
        "ell_minus": (0.35, 1.75),
        "ell_plus": (0.35, 2.25),
    }
    local_values: dict[str, float] = {}
    for name, (sigma, ell) in local_points.items():
        local_values[name], _ = phi_value(tau, weights, p_operator, sigma, ell)
    grad_sigma = (local_values["sigma_plus"] - local_values["sigma_minus"]) / 0.10
    grad_ell = (local_values["ell_plus"] - local_values["ell_minus"]) / 0.50

    assessment_rows = [
        {
            "assessment": "baseline_grid_max",
            "value": f"{float(best['Phi']):.17e}",
            "sigma": best["sigma"],
            "ell": best["ell"],
            "notes": "maximum over requested 10x8 baseline sweep at T=5000",
        },
        {
            "assessment": "inherited_step220_reference",
            "value": f"{STEP220_BASELINE:.17e}",
            "sigma": "0.35000000",
            "ell": "2.00000000",
            "notes": "Step 220 reference Phi_max at T=10000",
        },
        {
            "assessment": "center_value_T5000",
            "value": f"{local_values['center']:.17e}",
            "sigma": "0.35000000",
            "ell": "2.00000000",
            "notes": "baseline value at inherited maximizer",
        },
        {
            "assessment": "finite_difference_gradient_sigma",
            "value": f"{grad_sigma:.17e}",
            "sigma": "0.35 +/- 0.05",
            "ell": "2.00000000",
            "notes": "central finite difference using sigma=0.30,0.40",
        },
        {
            "assessment": "finite_difference_gradient_ell",
            "value": f"{grad_ell:.17e}",
            "sigma": "0.35000000",
            "ell": "2.0 +/- 0.25",
            "notes": "central finite difference using ell=1.75,2.25",
        },
    ]
    write_csv(ART / "universality_assessment_step276.csv", assessment_rows)

    payload = {
        "best_grid": best,
        "center_value_T5000": f"{local_values['center']:.17e}",
        "gradient_sigma": f"{grad_sigma:.17e}",
        "gradient_ell": f"{grad_ell:.17e}",
    }
    (ART / "compute_phi_max_sweep_output_step276.txt").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
